version: '3.9'

volumes:
  postgres:
  rabbitmq:

services:
  thriveactivewellness.api:
    image: ${DOCKER_REGISTRY-}thriveactivewelllnessapi
    container_name: ThriveActiveWellness.Api
    build:
      context: .
      dockerfile: src/API/ThriveActiveWellness.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  thriveactivewellness.database:
    image:  postgres:12-alpine
    container_name: ThriveActiveWellness.Database
    environment:
      - POSTGRES_DB=thriveactivewellness
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  thriveactivewellness.seq:
    image: datalust/seq:latest
    container_name: ThriveActiveWellness.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
  
  thriveactivewellness.redis:
    image: redis:latest
    container_name: ThriveActiveWellness.Redis
    restart: always
    ports:
      - 6379:6379
  
  thriveactivewellness.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ThriveActiveWellness.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686

  thriveactivewellness.queue:
    image: rabbitmq:management-alpine
    container_name: ThriveActiveWellness.Queue
    hostname: thriveactivewellness-queue
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672